artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer_data.zip
  local_data_file: artifact/data_ingestion/data.zip
  unzip_dir: artifact/data_ingestion
  